
modules-search:
  - local

modules:
  - name: welcome
    exec: welcome
  - name: locale
    exec: locale
  - name: keyboard
    exec: keyboard
  - name: partition
    exec: partition
  - name: users
    exec: users
  - name: summary
    exec: summary

sequence:
  - show: [welcome, locale, keyboard, partition, users, summary]
  - exec: [partition, mount, unpackfs, networkcfg, users, postcfg]

branding: kilasos

prompt-install: false

# Additional settings
show-full-config: false
debug: false
log-level: info
